#pragma kernel CSMain

uint3 Dims;

float scale;
float wave;
float peak;
float width;
float height;

float basinRadius;
float wallStartRadius;
float wallHeight;
float wallSteepness;

RWStructuredBuffer<float> Voxels;

[numthreads(8,8,8)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (any(id >= Dims)) return;

    uint index = id.x + Dims.x * (id.y + Dims.y * id.z);

    // 空気が一切存在しない「すべて地中 (Solid)」の空間にする
    // 密度 (Density) をすべてのボクセルで正の値 (1.0) に設定
    Voxels[index] = 1.0f;
}
